### ISSUE TITLE
About your jde model

### ISSUE THREAD

**Issue by q1vs5k5** [ZhangwenguangHikvision/YoloV5_JDE_TensorRT_for_Track#2]
I'd like to know about the difference between your jde model and the official model in which the 3 * (5 + classes_num) + embedding dimensions feature directly from the last same convolution  simultaneously.

**Comment by ZhangwenguangHikvision** [comment]
I just changed the detection model in JDE to YOLOV5。

**Comment by ZhangwenguangHikvision** [comment]
I uploaded the CSTrack3_0.yaml。CSTrack3_0.yaml contains the JDE network structure。

**Comment by q1vs5k5** [comment]
Thank you for your generous sharing, and I will try to reproduce it。
